version: "3.8"

volumes:
  headscale-data:
  headscale-socket:

services:
  headscale:
    container_name: headscale
    image: headscale/headscale:${HEADSCALE_VERSION:-0.23.0-beta1}
    command: serve
    restart: always
    # pull_policy: always
    volumes:
      - .devcontainer/headscale.yaml:/etc/headscale/config.yaml:ro
      - headscale-data:/var/lib/headscale:rw
      - headscale-socket:/var/run/headscale:rw

  hsadm:
    container_name: hsadm-backend
    image: hsadm:dev
    pull_policy: never
    restart: always
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile.backend
    ports:
      - 8000:8000/tcp
      # - 5173:5713/tcp # frontend
    environment:
      HSADM_CONFIG_PATH: /etc/headscale/config.yaml
      HSADM_UNSAFE_DISABLE_AUTHENTICATION: true
    volumes:
      # - .:/work:cached
      - .devcontainer/headscale.yaml:/etc/headscale/config.yaml:ro
      - headscale-socket:/var/run/headscale:ro
    depends_on:
      - headscale

  # headscale-admin-dev:
  #   container_name: headscale-admin-frontend
  #   restart: always
  #   network_mode: service:hsadm # share a network stack with the backend
  #   build:
  #     context: ./frontend
  #     dockerfile: ../.devcontainer/Dockerfile.frontend
  #   volumes:
  #     - ./frontend:/work:cached
  #   depends_on:
  #     - hsadm
