version: "3.8"

volumes:
  headscale-data:
  headscale-socket:

services:
  headscale:
    container_name: headscale
    image: headscale/headscale:${HEADSCALE_VERSION:-0.22.3}
    command: headscale serve
    restart: always
    # pull_policy: always
    volumes:
      - $PWD/.devcontainer/headscale.yaml:/etc/headscale/config.yaml:ro
      - headscale-data:/var/lib/headscale:rw
      - headscale-socket:/var/run/headscale:rw

  headscale-admin:
    container_name: headscale-admin-backend
    restart: always
    image: headscale-admin-backend:latest
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile.backend
    ports:
      - 8000:8000/tcp
      - 5173:5713/tcp # frontend
    volumes:
      # - .:/work:cached
      - headscale-socket:/var/run/headscale:ro

  headscale-admin-dev:
    container_name: headscale-admin-frontend
    restart: always
    network_mode: service:headscale-admin # share a network stack with the backend
    build:
      context: ./frontend
      dockerfile: ../.devcontainer/Dockerfile.frontend
    volumes:
      - ./frontend:/work:cached
