version: "3.9" # legacy
name: headscale

volumes:
  headscale-data:
  headscale-socket:

services:
  headscale:
    image: headscale/headscale:${HEADSCALE_VERSION:-0.23.0-beta1}
    container_name: headscale
    restart: always
    command: serve
    volumes:
      - $PWD/.devcontainer/headscale.yaml:/etc/headscale/config.yaml:ro
      - headscale-data:/var/lib/headscale:rw
      - headscale-socket:/var/run/headscale:rw

  headscale-admin:
    image: ghcr.io/rickli-cloud/headscale-admin:${HEADSCALE_ADMIN_VERSION:-latest}
    container_name: headscale-admin
    restart: always
    environment:
      HSADM_CONFIG_PATH: /headscale.yaml
      HSADM_UNSAFE_DISABLE_AUTHENTICATION: true
    volumes:
      - $PWD/.devcontainer/headscale.yaml:/headscale.yaml:ro
      - headscale-socket:/var/run/headscale:ro
    ports:
      - 8000:8000
    depends_on:
      - headscale
